name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

  schedule:
    - cron: '30 20 * * *'   # 2:00 AM IST


jobs:

  # -------------------------
  # SMOKE (runs on every push)
  # -------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Smoke Tests
        run: mvn clean test -DsuiteXmlFile=testng-smoke.xml

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Smoke-Reports
          path: |
            reports
            screenshots
            test-output


  # -------------------------
  # REGRESSION (nightly only)
  # -------------------------
  regression:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Regression Tests
        run: mvn clean test -DsuiteXmlFile=testng-regression.xml

      - name: Upload Regression Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Regression-Reports
          path: |
            reports
            screenshots
            test-output
